<!doctype html>
<html lang="ar" dir="rtl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>لوحة إدارة أمان</title>@vite(['resources/css/app.css'])</head>
<body class="app-page admin-page">
<aside class="admin-side"><img src="{{ asset('images/aman/logo.png') }}" alt="أمان"><h2>إدارة أمان</h2><a href="#overview">نظرة عامة</a><a href="#bookings">الحجوزات</a><a href="#counselors">المرشدون</a><a href="#content">المحتوى</a><a href="/">عرض المنصة</a><form method="POST" action="{{ route('logout') }}">@csrf<button>تسجيل الخروج</button></form></aside>
<main class="admin-main">
    <div id="overview" class="admin-title"><div><span>لوحة التحكم</span><h1>مرحبًا بك في إدارة أمان</h1></div></div>
    @if(session('success'))<div class="account-alert">✓ {{ session('success') }}</div>@endif
    @if($errors->any())<div class="admin-errors"><b>تعذر حفظ البيانات:</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="admin-stats"><article><strong>{{ $users->count() }}</strong><span>حساب مجهول</span></article><article><strong>{{ $bookings->count() }}</strong><span>طلب حجز</span></article><article><strong>{{ $counselors->count() }}</strong><span>مرشد وأخصائي</span></article><article><strong>{{ $services->count()+$programs->count() }}</strong><span>خدمة وبرنامج</span></article></div>

    <section id="bookings" class="admin-card"><h2>طلبات الحجز</h2><div class="admin-table">@forelse($bookings as $booking)<div class="admin-row"><span>#{{ $booking->id }}</span><b>{{ $booking->user->alias }}</b><span>{{ $booking->counselor?->name ?? 'دون تحديد' }}</span><form method="POST" action="{{ route('admin.bookings.update',$booking) }}">@csrf @method('PATCH')<select name="status"><option value="pending" @selected($booking->status==='pending')>قيد المراجعة</option><option value="accepted" @selected($booking->status==='accepted')>مقبول</option><option value="completed" @selected($booking->status==='completed')>مكتمل</option><option value="cancelled" @selected($booking->status==='cancelled')>ملغى</option></select><select name="counselor_id" required><option value="">اختر المرشد</option>@foreach($counselors as $counselor)<option value="{{ $counselor->id }}" @selected($booking->counselor_id===$counselor->id)>{{ $counselor->name }}</option>@endforeach</select><input type="datetime-local" name="scheduled_at" value="{{ $booking->scheduled_at?->format('Y-m-d\TH:i') }}" title="موعد الجلسة"><input type="url" name="meeting_url" value="{{ $booking->meeting_url }}" placeholder="رابط الاجتماع https://..." dir="ltr"><button>حفظ</button></form></div>@empty<p>لا توجد حجوزات بعد.</p>@endforelse</div></section>

    <section id="counselors" class="admin-card counselors-management">
        <div class="admin-section-head"><div><span>إدارة الفريق</span><h2>المرشدون والأخصائيون</h2><p>عرض وتحديث معلومات المرشدين الظاهرة للمستخدمين.</p></div><button class="admin-primary" type="button" data-new-counselor>+ إضافة مرشد جديد</button></div>
        <div class="admin-counselor-grid">
        @forelse($counselors as $counselor)
            <article class="admin-counselor-card">
                <div class="admin-counselor-top"><div class="admin-counselor-avatar">{{ mb_substr($counselor->name,0,1) }}</div><span class="admin-availability {{ $counselor->active?'active':'inactive' }}">● {{ $counselor->active?'ظاهر في المنصة':'غير نشط' }}</span></div>
                <h3>{{ $counselor->name }}</h3><p class="counselor-job">{{ $counselor->title }}</p>
                <div class="admin-counselor-facts"><span><b>{{ $counselor->experience_years ?? '—' }}</b> سنوات خبرة</span><span><b>{{ $counselor->rating }}</b> التقييم</span></div>
                <dl><div><dt>التخصصات</dt><dd>{{ $counselor->specialties ?: 'لم تُضف' }}</dd></div><div><dt>المؤهلات</dt><dd>{{ $counselor->qualifications ?: 'لم تُضف' }}</dd></div><div><dt>اللغات</dt><dd>{{ $counselor->languages ?: 'لم تُضف' }}</dd></div><div><dt>نبذة</dt><dd>{{ $counselor->bio ?: 'لا توجد نبذة تعريفية بعد.' }}</dd></div></dl>
                <div class="counselor-login-summary"><small>اسم الدخول</small><b dir="ltr">{{ $counselor->user?->username ?? 'لا يوجد حساب' }}</b></div><div class="admin-counselor-actions"><button type="button" class="edit-counselor" data-counselor='@json(array_merge($counselor->toArray(),["username"=>$counselor->user?->username]))'>تعديل البيانات</button><form method="POST" action="{{ route('admin.counselors.destroy',$counselor) }}" onsubmit="return confirm('هل تريد حذف المرشد {{ addslashes($counselor->name) }}؟ لن يمكن التراجع عن ذلك.')">@csrf @method('DELETE')<button class="delete-counselor">حذف</button></form></div>
            </article>
        @empty<div class="admin-empty">لا يوجد مرشدون. أضف أول مرشد للمنصة.</div>@endforelse
        </div>
    </section>

    <section id="content" class="admin-card"><h2>المحتوى المنشور</h2><div class="content-counts"><span>{{ $services->count() }} استشارة</span><span>{{ $programs->count() }} برامج دعم</span><span>{{ $counselors->count() }} مرشدين</span></div></section>
    @include('partials.system-footer')
</main>

<div class="admin-counselor-modal" id="counselorModal" aria-hidden="true"><div class="admin-modal-backdrop"></div><section><button class="admin-modal-close" type="button">×</button><span>بيانات المرشد</span><h2 id="counselorModalTitle">إضافة مرشد جديد</h2><form method="POST" action="{{ route('admin.counselors.store') }}" id="counselorForm">@csrf<div id="methodField"></div><div class="admin-form-grid"><label>اسم المرشد<input name="name" required maxlength="100"></label><label>المسمى المهني<input name="title" required maxlength="150" placeholder="أخصائي ومرشد نفسي"></label><label>اسم المستخدم للدخول<input name="username" dir="ltr" required maxlength="50" placeholder="COUNSELOR-01"></label><label>كلمة المرور الموحدة<input value="AMAN_123" dir="ltr" readonly></label><label>سنوات الخبرة<input name="experience_years" type="number" min="0" max="70"></label><label>التقييم<input name="rating" type="number" value="5" min="0" max="5" step="0.1" required></label><label class="full">التخصصات<input name="specialties" maxlength="500" placeholder="الدعم النفسي، الإرشاد الأسري..."></label><label class="full">المؤهلات<textarea name="qualifications" maxlength="1000" placeholder="الشهادات العلمية والمهنية"></textarea></label><label class="full">اللغات<input name="languages" maxlength="255" placeholder="العربية، الإنجليزية"></label><label class="full">نبذة تعريفية<textarea name="bio" maxlength="2000" placeholder="نبذة مختصرة تظهر للمستخدم"></textarea></label><label class="admin-active-check full"><input name="active" type="checkbox" value="1" checked> إظهار المرشد في المنصة وإتاحة الحجز معه</label></div><button class="admin-save-counselor">حفظ بيانات المرشد</button></form></section></div>
<script>
const bookingLocations=@json($bookings->pluck('location_url','id'));
document.querySelectorAll('#bookings .admin-row').forEach(row=>{const id=row.querySelector(':scope > span')?.textContent.replace('#','').trim(),bookingForm=row.querySelector('form'),meetInput=bookingForm?.elements.meeting_url;if(!bookingForm||!meetInput)return;meetInput.placeholder='رابط Google Meet للجلسة الأونلاين';meetInput.pattern='https://meet\\.google\\.com/.*';const locationInput=document.createElement('input');locationInput.type='url';locationInput.name='location_url';locationInput.dir='ltr';locationInput.placeholder='رابط موقع الجلسة الحضورية';locationInput.value=bookingLocations[id]||'';bookingForm.insertBefore(locationInput,bookingForm.querySelector('button'));});
const counselorModal=document.getElementById('counselorModal'),form=document.getElementById('counselorForm'),methodField=document.getElementById('methodField'),storeUrl=@json(route('admin.counselors.store'));
function openCounselor(data=null){form.reset();form.action=data?`${storeUrl}/${data.id}`:storeUrl;methodField.innerHTML=data?'<input type="hidden" name="_method" value="PATCH">':'';document.getElementById('counselorModalTitle').textContent=data?'تعديل بيانات المرشد':'إضافة مرشد جديد';if(data){['name','title','username','experience_years','rating','specialties','qualifications','languages','bio'].forEach(key=>form.elements[key].value=data[key]??'');form.elements.active.checked=Boolean(data.active)}else{form.elements.rating.value=5;form.elements.active.checked=true}counselorModal.classList.add('open');counselorModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCounselor(){counselorModal.classList.remove('open');counselorModal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelector('[data-new-counselor]').onclick=()=>openCounselor();document.querySelectorAll('.edit-counselor').forEach(button=>button.onclick=()=>openCounselor(JSON.parse(button.dataset.counselor)));document.querySelector('.admin-modal-close').onclick=closeCounselor;document.querySelector('.admin-modal-backdrop').onclick=closeCounselor;document.addEventListener('keydown',event=>{if(event.key==='Escape')closeCounselor()});
</script>
</body></html>
